FROM centos

# Add "uname" command
RUN uname -a > info.txt

# Sleep for 1000 seconds
CMD ["sleep", "1000"]


#docker build -t uname .
#docker run -d  --name uname-container uname
#docker tag uname <username>/uname
#docker login
#docker push <your-docker-hub-username>/uname
